// Generated by CoffeeScript 1.9.3
(function() {
  var addMyUUIDToStorage, allOpenGraphs;

  $(function() {
    document.addEventListener('ping', function(e) {
      return addMyUUIDToStorage;
    });
    document.addEventListener('newGraph', function(e) {
      return alert(e.detail);
    });
    return $(document).on("click", "#do_products", function() {
      return alert(allOpenGraphs());
    });
  });

  $(function() {
    return $(window).bind('storage', function(event) {
      if (event.key === 'requestOpenGraphs') {
        return addMyUUIDToStorage();
      }
    });
  });

  allOpenGraphs = function() {
    localStorage.setObject('allOpenGraphs', {});
    localStorage.setItem('requestOpenGraphs', Math.random());
    addMyUUIDToStorage();
    return localStorage.getObject('allOpenGraphs');
  };

  addMyUUIDToStorage = function() {
    var all;
    all = localStorage.getObject('allOpenGraphs');
    all[uuid] = 1;
    return localStorage.setObject('allOpenGraphs', all);
  };

  Storage.prototype.setObject = function(key, value) {
    return this.setItem(key, JSON.stringify(value));
  };

  Storage.prototype.getObject = function(key) {
    var value;
    value = this.getItem(key);
    return value && JSON.parse(this.getItem(key));
  };

}).call(this);

//# sourceMappingURL=panda.js.map
